### ISSUE TITLE
Tab focus issues.

### ISSUE THREAD

**Issue by facelessuser** [facelessuser/TabsExtra#15]
In general TabExtra does everything it is supposed to.  But due to the way Sublime currently implements its views.  There are quirks.

Sublime implements normal views as views, but they are also sheets.  Image previews are just sheets.  Sadly, on top of that, Sublime does not implement a way that links sheets to to views, and frankly, the sheet API is pretty worthless as it offers nothing of value.  But sheets must be used to get the tab index as only sheet indexes are accurate (image previews don't show up in views so view index does not equal tab index).

For this reason TabsExtra has to translate views to sheets.  And since there is no link between views and sheets in the API, Tabs Extra has to loop through the views and focus them to get the associated sheet.  This may cause some mild quirks (mainly sometimes you will see two items highlighted in the sidebar).  But despite the quirks, the correct view should get focused as TabsExtra's algorithm has recently been improved to ensure such things are working as good as possible.

When moving a view to a different window etc., the correct view in the old window should become active, but it may not look like it.  This is partly due because of Sublime file preview views.  Sublime does't bother to expose any API to recognize a preview view.  Preview views seem to not trigger events you would expect and don't always behave quite like they should.  Usually focusing a different Sublime window, and refocusing the old window will show the correct view as active in this move tab scenario.  These are issues with the way Sublime does things, and these things force TabsExtra to do some hacky stuff to get things to feel right, but these are small, minor quirks.

So anyways, as of writing this, tab focus issues appear to be mainly minor.  Feel free to create an issue if some of the behaviors appear to be more critical, but if not, I will refer people here to read this.

**workaround sidebar**:  multiple items can become highlighted in the sidebar.  This is because of the way sublime does file previews, and it is a PITA to get working how it should.  Because of this, **I may end up removing specialized tab focusing on tab close**.  But if the multiple items in sidebar are an issue, disabling previews can resolve it.  If that doesn't sound acceptable, disabling TabsExtra will fix it :wink:.  Anyways, I am actively trying to come to a final solution.

**Comment by rudiedirkx** [comment]
Excellent! (Even though it doesn't all make a lot of sense to me =)) Do ST3 and TabsExtra update a the same time?

**Comment by facelessuser** [comment]
Not necessarily.  Package Control is responsible for updating TabsExtra.  Sadly, I haven't pushed the changes to the ST3 branch so Package Control can't see it yet.

I am always running off the dev (master) branch.  I do this so I can see how well things work before I push them to everyone else.  Because I run on the master, I manually update my branches.

Tonight I should push the initial changes.  In the coming weeks, I plan on evaluating the current tab focusing scenarios with the latest changes and possibly making some tweaks to get things working how they always should have been working.  Eventually I will require Sublime version 3068 or greater so can remove the legacy crap.  If all goes well, TabsExtra should be working smoothly.

**Comment by facelessuser** [comment]
I have been running through tab scenarios and it appears that on build 3068 that all known focus issues are resolved.  Any build below 3068 will continue to suffer from issues, but once the next public beta comes out (non dev build), I will require upgrades to the public beta if using TabsExtra.

I am very happy I get to close this issue without gutting features.

**Comment by rudiedirkx** [comment]
Can't wait to try it out. You're the best.

How do I change to the beta channel? I'm using stable now, currently build 3065.

**Comment by facelessuser** [comment]
Do you own a license?  You need to own a license for the dev channel.

**Comment by facelessuser** [comment]
If you have a license, you can install the latest dev from here http://www.sublimetext.com/3dev, and then you will get updates when new dev builds are available.  You can just install over your old one.

**Comment by mykmelez** [comment]
I see the merge to master 16 hours ago, and I've upgraded to ST3 3069 and then uninstalled/reinstalled TabsExtra from Package Control, so I now have version 2015.02.04.01.42.43. But I still see #21.

**Comment by facelessuser** [comment]
That is because I haven't added custom tab open handling.  I still need to determine how much work that would take and if i wasn't too add that.  *This* issue mainly deals with bugs related to existing tab focus features.

Maybe we should open a feature request.

**Comment by mykmelez** [comment]
> Maybe we should open a feature request.

Ok, I'm happy to do that, although I had thought #21 was one of those existing tab focus bugs! Erm, but perhaps I don't know exactly what you have in mind for a "custom tab open handling" feature.

My personal preference is quite basic: when fallback_focus is set to "right", as it is by default, I'd just like "Reopen Closed File" to reopen the file to the left of its previous location, so that the "close, reopen" sequence of operations (which I find myself doing multiple times a day) results in the reopened tab being in the same place as it was before I closed it.

For that, would it be sufficient to reopen #21, or would you rather implement a more general feature for specifying tab opening placement, and track that as a more general issue?

**Comment by facelessuser** [comment]
Sorry for the confusion; #11 is basically what you are requesting.  Reopen/open are the same as far as the code would be concerned.  So I would subscribe to that.  I should have pointed you there originally, but I thought Jon was never going to update the API to get around the focus issues I was having, so I was planning on killing all focus features...that is probably why I pointed you here.   Well things look more promising now, so I think custom open focus is possible.

**Comment by mykmelez** [comment]
Ok, I'm subscribed to that issue, thanks @facelessuser!
